In [2]:
import os
os.environ["JAX_PLATFORM_NAME"] = "cpu"

In [3]:
# Import netket library
import netket as nk

# Import Json, this will be needed to load log files
import json

# Helper libraries
import numpy as np
import matplotlib.pyplot as plt
import time

In [4]:
# Define a 1d chain
L = 3
g = nk.graph.Hypercube(length=L, n_dim=1, pbc=True)


In [5]:
# Define the Hilbert space based on this graph
# We impose to have a fixed total magnetization of zero 
hi = nk.hilbert.Spin(s=0.5, N=g.n_nodes)

In [6]:
# calling the Heisenberg Hamiltonian
ha = nk.operator.Heisenberg(hilbert=hi, graph=g)

In [7]:
ha.graph.adjacency_list()

[[1, 2], [0, 2], [0, 1]]

In [8]:
ha.operators

[array([[ 1.,  0.,  0.,  0.],
        [ 0., -1.,  2.,  0.],
        [ 0.,  2., -1.,  0.],
        [ 0.,  0.,  0.,  1.]]),
 array([[ 1.,  0.,  0.,  0.],
        [ 0., -1.,  2.,  0.],
        [ 0.,  2., -1.,  0.],
        [ 0.,  0.,  0.,  1.]]),
 array([[ 1.,  0.,  0.,  0.],
        [ 0., -1.,  2.,  0.],
        [ 0.,  2., -1.,  0.],
        [ 0.,  0.,  0.,  1.]])]

In [9]:
ha.get_conn(hi.all_states()[2])

(array([[-1.,  1., -1.],
        [ 1., -1., -1.],
        [-1., -1.,  1.]]),
 array([-1.,  2.,  2.]))

In [10]:
hi.all_states()[2]

array([-1.,  1., -1.])

In [11]:
ha.to_dense().shape

(8, 8)

In [13]:
ha.bond_ops

AttributeError: 'Heisenberg' object has no attribute 'bond_ops'

In [87]:
ha.to_dense()

array([[ 3.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0., -1.,  2.,  0.,  2.,  0.,  0.,  0.],
       [ 0.,  2., -1.,  0.,  2.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -1.,  0.,  2.,  2.,  0.],
       [ 0.,  2.,  2.,  0., -1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  2.,  0., -1.,  2.,  0.],
       [ 0.,  0.,  0.,  2.,  0.,  2., -1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  3.]])

In [89]:
ha.operators

[array([[ 1.,  0.,  0.,  0.],
        [ 0., -1.,  2.,  0.],
        [ 0.,  2., -1.,  0.],
        [ 0.,  0.,  0.,  1.]]),
 array([[ 1.,  0.,  0.,  0.],
        [ 0., -1.,  2.,  0.],
        [ 0.,  2., -1.,  0.],
        [ 0.,  0.,  0.,  1.]]),
 array([[ 1.,  0.,  0.,  0.],
        [ 0., -1.,  2.,  0.],
        [ 0.,  2., -1.,  0.],
        [ 0.,  0.,  0.,  1.]])]